name: Update Commit Graph

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python deps
        run: pip install matplotlib

      - name: Generate graph
        run: python scripts/commit_graph.py

      - name: Commit graph
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add commit_graph.png
          git commit -m "Update commit graph"
          git push
