# name: Update Commit Graph

# on:
#   push:
#   schedule:
#     - cron: "0 */6 * * *"

# jobs:
#   update-graph:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Install dependencies
#         run: pip install matplotlib

#       - name: Run script
#         run: python scripts/commit_graph.py

#       - name: Commit graph
#         run: |
#           git config --global user.name "github-actions"
#           git config --global user.email "actions@github.com"
#           git add commit_graph.png
#           git commit -m "Update commit graph" || echo "No changes"
#           git push
